# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/eldar_study',
                'doc_host': 'https://hgzech.github.io',
                'git_url': 'https://github.com/hgzech/eldar_study',
                'lib_path': 'eldar_study'},
  'syms': {'eldar_study.core': {'eldar_study.core.foo': ('core.html#foo', 'eldar_study/core.py')}}}
